### ISSUE TITLE
pwritev(2) hanging while writing about 500 KiB

### ISSUE THREAD

**Issue by foutrelis** [jwrdegoede/vboxsf#2] opened 2018-08-11 22:22 UTC
Adding this as a GitHub issue in order to better track it. I briefly mentioned it [here](https://bugzilla.redhat.com/show_bug.cgi?id=1481630#c80).

This example code appears to hang: https://www.virtualbox.org/ticket/17716#comment:16

Reproducible on Arch and Fedora.

**Comment by xnoreq** [comment] 2019-01-19 13:04
The pwritev hang/loop/corruption issue with shared folders still exists in linux 4.20.3 with virtualbox 6.0.2 (virtualbox-guest-modules-arch, virtualbox-guest-utils-nox).

**Comment by jwrdegoede** [comment] 2019-03-05 15:14
Ok, so I've finally gotten around to debugging this, sorry for taking so long and thank you for the reproducer.

This only happens when using my cleaned-up standalone version of vboxsf, which is intended for merging upstream from:  https://github.com/jwrdegoede/vboxsf/

So it seems that you are seeing this problem because the virtualbox-guest-modules-arch is using my version of vboxsf starting with the troublesome version. Therefor I believe that this ticket can be closed as this is not an upstream virtualbox bug.

During the refactoring / cleanup of the code to prepare it for merging into the mainline kernel I messed up the sf_write_end function return's value. Unlike the other mmap handling functions it is supposed to return the number of bytes written on success or 0 on error, instead of 0 on success and negative errno on error (which is documented nowhere). With that fixed your reproducer works as expected.

This is fixed in commit 6738af37c935f3d9b0db138678c2cd3d8bc1fc99

**Closed as completed by jwrdegoede** 2019-03-05 15:14 UTC
